## LATIHAN

Diketahui Array :[12 10 04] Tanggal Lahir

                 [74 23 91]  Digit No Hp

Lakukanlah Operasi:
                

1. Perkalian Matrix

In [11]:
# TTL   : 12 oktober 2004
# No Hp : 081292742391

import numpy as np

A = np.array([[1,2],[1,0],[0,4]])
B = np.array([[7,4],[2,3],[9,1]])

kali = A * B
print(kali)

[[7 8]
 [2 0]
 [0 4]]


2. Pengurangan Matrix

In [10]:
import numpy as np

A = np.array([[1,2],[1,0],[0,4]])
B = np.array([[7,4],[2,3],[9,1]])

kurang = A - B
print(kurang)

[[-6 -2]
 [-1 -3]
 [-9  3]]


3. Transpose Matrix

In [9]:
import numpy as np

A = np.array([[1,2],[1,0],[0,4]])
B = np.array([[7,4],[2,3],[9,1]])

transpose_A = np.transpose(A)
transpose_B = np.transpose(B)

print(transpose_A)
print(transpose_B)

[[1 1 0]
 [2 0 4]]
[[7 2 9]
 [4 3 1]]


4. Nilai Invers

In [5]:
import numpy as np

A = np.array([[1,2],[1,0]])
B = np.array([[7,4],[2,3]])


invers_A = np.linalg.inv(A)
invers_B = np.linalg.inv(B)

print("\nInvers matrix A :")
print("\nInvers matrix B :")
print(invers_A)
print(invers_B)



Invers matrix A :

Invers matrix B :
[[ 0.   1. ]
 [ 0.5 -0.5]]
[[ 0.23076923 -0.30769231]
 [-0.15384615  0.53846154]]


5. Nilai Determinan

In [4]:
import numpy as np

A = np.array([[1,2],[1,0]])
B = np.array([[7,4],[2,3]])

determinant_A = np.linalg.det(A)
determinant_B = np.linalg.det(B)
print("Determinan dari matrix A:", determinant_A)
print("Determinan dari matrix B:", determinant_B)

Determinan dari matrix A: -2.0
Determinan dari matrix B: 13.0
